Issue 11
OpenFabrics/sunfish_library_reference pull request #15
Opened 2024-01-12 14:46 UTC by mgazz

With these changes the patch method takes as input only the changes that we want to apply to the target object. I also updated the test to fit the new mechanism.

See #11  for a more detailed description of the problem.

2024-02-02 07:26 UTC, mgazz commented
@christian-pinto thank you for the review. I rebased the branch and added verified commits. I'll be available in case on any question.

2024-02-08 09:23 UTC, christian-pinto commented
@mjaguil could you please have a look at this PR?

2024-02-08 14:45 UTC, dledford commented on sunfish/lib/core.py
> +    def patch_object(self, path,payload):
Whitespace inconsistency is annoying.  Doubly so when you add an inconsistency in the middle of a single statement :-/

2024-02-08 14:47 UTC, dledford requested changes
Comments on the respective code lines

2024-02-08 14:47 UTC, dledford commented on sunfish/lib/core.py
> +        return self.storage_backend.patch(path,payload)
More here

2024-02-08 14:47 UTC, dledford commented on sunfish/lib/exceptions.py
> +        message = "Attribute " + attribute_name+ " not found."
More here.

2024-02-08 14:47 UTC, dledford commented on sunfish/storage/backend_FS.py
> +    def patch(self, path: str, payload:json):
More here

2024-02-09 15:13 UTC, mgazz commented
@dledford thank you for the feedback. I will update as spacing to make it more consistent.

2024-02-23 11:03 UTC, mgazz commented on sunfish/lib/core.py
> +    def patch_object(self, path,payload):
Fixed in 4e3226cd76e3e06811f6c4e58bb13ab288c8e198

2024-02-23 11:03 UTC, mgazz commented on sunfish/lib/core.py
> +        return self.storage_backend.patch(path,payload)
Fixed in 4e3226cd76e3e06811f6c4e58bb13ab288c8e198

2024-02-23 11:03 UTC, mgazz commented on sunfish/lib/exceptions.py
> +        message = "Attribute " + attribute_name+ " not found."
Fixed in d102571eb4fcbf0640d50cfd77489af740e0275a

2024-02-23 11:03 UTC, mgazz commented on sunfish/storage/backend_FS.py
> +    def patch(self, path: str, payload:json):
Fixed in d102571eb4fcbf0640d50cfd77489af740e0275a

2024-02-24 05:17 UTC, dledford approved these changes
Thanks for updating the style issues

2024-02-28 13:36 UTC, christian-pinto reviewed
Looks good to me

2024-02-28 13:37 UTC, christian-pinto approved these changes

2024-02-28 13:38 UTC, merged