Added support for storage backend and event handler plugins
OpenFabrics/sunfish_library_reference pull request #29
Opened 2024-06-24 14:55 UTC by christian-pinto

This pull request adds support for dynamically loaded plugins

The Sunfish core library uses a plugin mechanism that allows dynamic loading of certain classes. This helps users with updating the behavior of the sunfish library without having to modify its core classes. At the moment we support plugins for the storage backend and for the redfish event handlers. Plugins are implemented as namespaced packages and must be placed in a folder at the top of the project named "sunfish_plugins", with subfolders named "storage" and/or "event_handlers". The python packages defined inside each subfolder are totally user defined.

```bash
 ── sunfish_plugins
         ├── storage
         │    └──my_storage_package     <--- User defined
         │        ├── __init__.py
         │        └── my_storage_backend.py
         └── event_handlers
              └──my_handler_package     <--- User defined
                  ├── __init__.py
                  └── my_handler.py
```
 
When initializing the Sunfish libraries can load their storage or event handler plugin by specifying them in  the configuration as in the below example: 
```json
"storage_backend" : {
    "module_name": "storage.my_storage_package.my_storage_backend",
    "class_name": "StorageBackend"
},
"event_backend" : {
    "module_name": "event-handlers.my_handler_package.my_handler",
    "class_name": "EventHandler"
},
```
In both cases "class_name" represents the name of the class that is initialized and implements the respective interface.

2024-06-25 14:33 UTC, dledford requested changes
I think it would be better if the loading sequence was "test conf, try to load conf module, on failure fall through to default conf stanza and try to load the default, and only fail once both have failed".  This would require changes in the test unit too.

2024-06-25 14:33 UTC, dledford commented on sunfish/lib/core.py
> +        if "storage_backend" not in conf:
I would change the flow of all three of these loaders.  Instead of conf or default, try load, fail if not found, I would do test conf, load if in conf, check to see if found, default to fallback if no conf or not found.  That way a broken conf file won't keep us from loading the default and being (hopefully) minimally useful

2024-06-26 08:48 UTC, christian-pinto commented on sunfish/lib/core.py
> +        if "storage_backend" not in conf:
Good point. I will make it so that it starts from conf, if available, and fall-back to default before failing. Just FYI, the text in the comment is showing the conf file and not the actual load for loading plugins.

2024-06-26 09:14 UTC, christian-pinto commented on sunfish/lib/core.py
> +        if "storage_backend" not in conf:
@dledford done

2024-06-26 13:17 UTC, dledford approved these changes

2024-07-01 10:27 UTC, christian-pinto commented
@cayton @mjaguil @mgazz could any of you review this PR?

2024-07-01 14:53 UTC, rherrell commented on sunfish/lib/core.py
> +        # When initializing the Sunfish libraries can load their storage or event handler plugin by specifying them in
as discussed in our Sunfish working meeting, maybe the forward_to_manager modules should be a plugin separate from the object_handlers plugin.   This way different Agents can install different 'forward_to_manager' plugins while using the same object_handler plugins.   Agents (and even specialized versions of Sunfish Core) might use their 'forward_to_manager' plugins to do pre-processing of Redfish objects in custom manner while still using Sunfish Core object handlers of the final Redfish object model.

2024-07-01 14:57 UTC, rherrell commented on sunfish/lib/core.py
> +            self.objects_handler.forward_to_manager(SunfishRequestType.PATCH, path, payload=payload)
again, let's consider moving the 'forward_to_manager' pre-processing calls to a separate plugin from the more general object_handlers.  Object_handlers give us unique handling for each object type, but foward_to_manager gives us unique object pre-processing.  It would be nice to have them as orthogonal plug-ins.

2024-07-02 16:50 UTC, cayton commented on sunfish_plugins/objects_handlers/sunfish_server/redfish_object_handler.py
> +                if "Oem" not in agent_response:
Very minor nit - let's rationalize the capitalization of terms (e.g., "Collection"/"collection").

2024-07-02 16:51 UTC, cayton approved these changes
Good review in the Monday 07/01 WG meeting. Agree with Russ's ideas.

2024-07-04 16:03 UTC, christian-pinto commented on sunfish/lib/core.py
> +        # When initializing the Sunfish libraries can load their storage or event handler plugin by specifying them in
fixed in last commit

2024-07-04 16:03 UTC, christian-pinto commented on sunfish/lib/core.py
> +            self.objects_handler.forward_to_manager(SunfishRequestType.PATCH, path, payload=payload)
fixed in last commit

2024-07-04 16:03 UTC, christian-pinto commented on sunfish_plugins/objects_handlers/sunfish_server/redfish_object_handler.py
> +                if "Oem" not in agent_response:
fixed in last commit

2024-07-04 16:04 UTC, christian-pinto commented
@rherrell, @cayton thanks for your review.

Please have a look at the new version of the code and let me know if it looks good now. If it does, please complete the github review process and approve the PR so that I can merge it.

2024-07-05 08:18 UTC, merged