Events
OpenFabrics/sunfish_library_reference pull request #7
Opened 2023-11-22 10:01 UTC by erika-rosaverde

New module added that handle the events and the subscriptions. In particular, the new module contains the event_handler class that loads the subscriptions (if they are already stored), validates a new subscription before to store it, forwards the events to the subscribers. 
Core generate an unique ID that is assigned to the new objects when POST is called.
Backend_FS and tests has been updated to work with the new module.

2023-11-22 14:59 UTC, mjaguil approved these changes

2023-11-22 21:06 UTC, christian-pinto requested changes
Few things need to be improved but it is overall looking fine.

2023-11-22 21:06 UTC, christian-pinto commented on sunfishcorelib/events/event_handler.py
> +                              to_forward.append(id)
just use `extend()`
```python
to_forward.extend(subscribtions["ResourceTypes"][type])
```

same applies to all similar cases below

2023-11-22 21:06 UTC, christian-pinto commented on tests/test_sunfishcore_library.py
> +    def test_expected_request_handler(self, httpserver: HTTPServer):
We should test having multiple subscriptions and handling an event targeting only one of them. To make sure the data structure we use for figuring out who to send to works fine.

2023-11-22 21:06 UTC, christian-pinto commented on tests/test_utils.py
>  #     modification_time = time.ctime(os.path.getctime(path))
Remove commented code unless we have an explanation why we need it there as a comment.

2023-11-23 15:28 UTC, christian-pinto approved these changes

2023-11-24 18:39 UTC, christian-pinto commented
@mjaguil Could you please complete your review?

2023-11-24 18:54 UTC, mjaguil commented
I’ll get it done, right now…


From: Christian Pinto ***@***.***>
Date: Friday, November 24, 2023 at 11:40 AM
To: OpenFabrics/sunfish_library_reference ***@***.***>
Cc: Aguilar, Michael James ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [OpenFabrics/sunfish_library_reference] Events (PR #7)

@mjaguil<https://github.com/mjaguil> Could you please complete your review?

—
Reply to this email directly, view it on GitHub<https://github.com/OpenFabrics/sunfish_library_reference/pull/7#issuecomment-1825989758>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AEGDPAGY5TXJQUZLYLSTB7LYGDSXNAVCNFSM6AAAAAA7V6KXXGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRVHE4DSNZVHA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-24 18:56 UTC, mjaguil approved these changes

2023-11-24 20:07 UTC, merged